name: CI/CD Chinook

on:
  push:
    branches:
      - main

jobs:

  build-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Angular
        run: npm run build -- --configuration production

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist/chinook-frontend/browser


  deploy-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest

    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: dist

      - name: Copy build to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 3.235.229.64
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*"
          target: "/tmp/chinook-dist"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 3.235.229.64
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rm -rf /var/www/html/*
            sudo cp -r /tmp/chinook-dist/* /var/www/html/
            sudo systemctl restart nginx
            echo "Frontend deployed successfully"